
let ARROW_LEFT = 37;
let ARROW_UP = 38;
let ARROW_RIGHT = 39;
let ARROW_DOWN = 40;
let SPACEBAR = 32;

let	BOARD_WIDTH = 10;
let	BOARD_HEIGHT = 24;
let	START_X = 3;
let	START_Y = 0;
let	QUEUE_LENGTH = 6;
let actions = {
		SHIFT_LEFT: ARROW_LEFT,
		SHIFT_RIGHT: ARROW_RIGHT,
		SHIFT_DOWN: ARROW_DOWN,
		ROTATE: ARROW_UP,
		HARD_DROP: SPACEBAR
}
let GAME_STATE = {
	PLAYING: 0,
	PAUSED: 1,
	GAMEOVER: 2
}
export {
	BOARD_WIDTH,
	BOARD_HEIGHT,
	START_X,
	START_Y,
	QUEUE_LENGTH,
	actions,
	GAME_STATE
}